name 'rexbackup'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rexbackup'
long_description 'Installs/Configures rexbackup'
version '0.1.0'
