name 'rexbackup'
maintainer 'David King'
maintainer_email 'david@rexden.us'
license 'all_rights'
description 'Installs/Configures rexbackup'
long_description 'Installs/Configures rexbackup'
version '0.1.0'

depends 'sysctl'
depends 'rexcore'
